apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-todo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: my-todo-app
        image: 620603608090.dkr.ecr.ap-southeast-1.amazonaws.com/django
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-app
    k8s-app: todo-app
  name: todo-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8082
  type: LoadBalancer
  selector:
    app: todo-app
